### ISSUE TITLE
Sentiment engine failed when submitting a file for test mode

### ISSUE THREAD

**Issue by quynhdang-vt** [veritone/V3-Engine-Examples#8]
# Steps

Following the instruction to create the sentiment engine, then run `make up-test`.  

From a browser instance, go to http://localhost:9090

Submit a .txt file, with MIME type = text/plain

Submit request.  

Get this back on the form:

```
500 Internal Server Error
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

The terminal where make was running show the following

```
Location: ~/go/src/github.com/veritone/V3-Engine-Examples/python/sentimentgit:(master)  make up-test
docker run --rm -e "VERITONE_TESTMODE=true" -p 9090:9090 -p 8080:8080 "sentiment-sample-chunk-v-3"
2021/05/07 19:41:58 Veritone Engine Toolkit [linux/amd64] 0.0.0:HEAD:b6e1b627c20489463f7dca463200649af1000222, built on 2021-04-27_19:09:35 (1619550607)
2021/05/07 19:41:58 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2021/05/07 19:41:58 HOSTNAME=4e51cdf9e5cd
2021/05/07 19:41:58 VERITONE_TESTMODE=true
2021/05/07 19:41:58 PYTHONPATH=:/app
2021/05/07 19:41:58 LC_ALL=C.UTF-8
2021/05/07 19:41:58 LANG=C.UTF-8
2021/05/07 19:41:58 VERITONE_WEBHOOK_READY=http://0.0.0.0:8082/ready
2021/05/07 19:41:58 VERITONE_WEBHOOK_PROCESS=http://0.0.0.0:8082/process
2021/05/07 19:41:58 VERITONE_DISABLE_CHUNK_DOWNLOAD=true
2021/05/07 19:41:58 HOME=/root
time="2021-05-07T19:41:58Z" level=debug msg="EI [EI:91782058-c9c5-4151-b79d-bd2f266e8412] engine: running"
time="2021-05-07T19:41:58Z" level=debug msg="EI [EI:91782058-c9c5-4151-b79d-bd2f266e8412] WARNING: Test mode (remove VERITONE_TESTMODE before putting into production)"
time="2021-05-07T19:41:58Z" level=debug msg="EI [EI:91782058-c9c5-4151-b79d-bd2f266e8412] running subprocess for testing..."
no push IP configured ... not pushing to pushgatewway
time="2021-05-07T19:41:58Z" level=debug msg="EI [EI:91782058-c9c5-4151-b79d-bd2f266e8412] running test console..."

	The Engine Toolkit Test Console is now running.

	Go to: http://localhost:9090/
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://0.0.0.0:8082/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [07/May/2021 19:42:17] "GET /ready HTTP/1.1" 200 -
INFO:app:Input chunk is text/plain
INFO:app:Reading from
ERROR:app:Exception on /process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/app.py", line 53, in process
    with urllib.request.urlopen(cacheUri) as f:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 511, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.6/urllib/request.py", line 329, in __init__
    self.full_url = url
  File "/usr/lib/python3.6/urllib/request.py", line 355, in full_url
    self._parse()
  File "/usr/lib/python3.6/urllib/request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: ''
INFO:werkzeug:127.0.0.1 - - [07/May/2021 19:44:20] "POST /process HTTP/1.1" 500 -
```

apparently cacheUri was not set?

**Comment by kevmurray** [comment]
Fixed with https://github.com/veritone/V3-Engine-Examples/pull/17
